### ISSUE TITLE
Please add support for \r\n

### ISSUE THREAD

**Issue by jkerdreux-imt** [wtarreau/bootterm#1] opened 2020-12-14 15:57 UTC
Some devices (a marvin 3D printer here) send both \r\n as a EOL. Could you please add a flag to treat this like a simple \n in terminal. (\r\n is normal in capture file).

**Comment by wtarreau** [comment] 2020-12-14 21:40
What problem does it pose to you to have CRLF on the terminal ? Most of the devices I use here already send CRLF and the terminal renders them appropriately. I tried on my GRBL laser printer firmware which sends CRLF as well and it worked fine. The issue you'd have would be if you were running from a windows-like terminal which needs to have both when only LF is sent. But a CRLF received and displayed on a unix platform will not cause difficulties.

**Comment by jkerdreux-imt** [comment] 2020-12-14 23:26
It's just a pain in ass to read/use. See attached.

Thanks

**Comment by wtarreau** [comment] 2020-12-15 04:28
Unfortunately your attachment didn't work (or was dropped via the e-mail).

**Comment by wtarreau** [comment] 2021-01-25 15:29
Closing now as it's been 40 days without any update and the issue doesn't correspond to local observations (CRLF being sent by basically every device tested and fortunately not causing trouble). If you face an issue again, please reopen with a capture and/or an example of the problem.

**Comment by coelner** [comment] 2021-01-30 11:45
I like to open this issue and adapt it somehow if allowed.
I think it would be useful to optionally map a LF to a CRLF. some of the *nix derivates only send a LF, which (correctly) results in a stairs alike printout

**Comment by wtarreau** [comment] 2021-01-30 13:28
Again, I'm not opposed, but as I said I want a **concrete** example of a case where this happens. I'd really like to be able to reproduce it myself to test it. I've got plenty of different OSes and for now it appears that I'm always receiving CRLFs, even from boot loaders and microcontrollers, making me think that these are mapped to CRLF on the sending terminal. If you give me some info on your setup maybe I could trigger it and figure the best solution.

**Comment by coelner** [comment] 2021-01-30 13:44
```
bt /dev/ttyUSB1
Trying port /dev/ttyUSB1... Connected to /dev/ttyUSB1 at 115200 bps.
Escape character is 'Ctrl-]'. Use escape followed by '?' for help.
000020045: [SYSTEM] VBAT: 0.28 V
                                000025048: [SYSTEM] VBAT: 0.28 000030051: [SYSTEM] VBAT: 0.35 V
                                                                                               000035054: [SYSTEM] VBAT: 0.59 V
       000040057: [SYSTEM] VBAT: 0.82 V
                                       000045060: [SYSTEM] VBAT: 0.30 V
                                                                       000050063: [SYSTEM] VBAT: 0.28 V
                                                                                                       000055066: [SYSTEM] VBAT: 0.28 V
               000060069: [SYSTEM] VBAT: 0.28 V
                                               000065072: [SYSTEM] VBAT: 0.28 V
                                                                               000070075: [SYSTEM] VBAT: 0.28 V
                                                                                                               000075078: [SYSTEM] VBAT: 0.28 V
                       000080081: [SYSTEM] VBAT: 0.43 V
                                                       000085084: [SYSTEM] VBAT: 0.37 V
                                                                                       000090087: [SYSTEM] VBAT: 0.28 V
                                                                                                                       000095090: [SYSTEM] VBAT: 0.28 V

```

**Comment by wtarreau** [comment] 2021-01-30 18:44
OK, and for my knowledge, what device is this ?

**Comment by wtarreau** [comment] 2021-01-30 18:53
I'm asking because all the devices I have access to systematically emit the CR before the LF, look for example here:
```
$ xxd bootterm-20210130-194605.log
00000000: 0d0a 726f 6f74 4077 7274 3139 3030 3a7e  ..root@wrt1900:~
00000010: 2320 7072 696e 7466 2022 6162 5c6e 6364  # printf "ab\ncd
00000020: 2208 2008 5c6e 220d 0a61 620d 0a63 640d  ". .\n"..ab..cd.
00000030: 0a72 6f6f 7440 7772 7431 3930 303a 7e23  .root@wrt1900:~#
00000040: 20                                        
```
Interesting to see that when asking to send LF a CRLF was emitted, and playing with stty onlcr, ocrln etc doesn't change that, still trying to get one to produce this.

**Comment by wtarreau** [comment] 2021-01-30 18:53
OK I achieved it using `stty raw`, now I can play with it.

**Comment by wtarreau** [comment] 2021-01-30 19:47
Now done, please test again. You'll need to `export BT_PORT_CRLF=1` to remap LF to CRLF. CR to CRLF is 2.

**Comment by coelner** [comment] 2021-01-31 13:05
```
$ export BT_PORT_CRLF=1 && echo $BT_PORT_CRLF
1
$ ./bt /dev/ttyUSB1
Trying port /dev/ttyUSB1... Connected to /dev/ttyUSB1 at 115200 bps.
Escape character is 'Ctrl-]'. Use escape followed by '?' for help.
000110098: [SYSTEM] VBAT: 0.34 V
000115101: [SYSTEM] VBAT: 0.28 000150122: [SYSTEM] VBAT: 0.28 V
000155125: [SYSTEM] VBAT: 0.28 V
000160128: [SYSTEM] VBAT: 0.39 V
000165131: [SYSTEM] VBAT: 0.28 V
000170134: [SYSTEM] VBAT: 0.28 V
```
[the second line is broken, the lsat char 'V' is missing, therefore also the '\n']

In this case it was an ESP32, which was programmed with sprintf. But sometimes those cheap Bluetooth LE UART adapter show this too.

Thanks for implementing this

**Comment by wtarreau** [comment] 2021-01-31 18:13
OK, good point indeed about self-programmed devices. I'm even ashamed for not having thought about them given that I do also use some :-)  So may we close this issue ?

**Comment by jkerdreux-imt** [comment] 2021-02-01 00:24
Works fine w/ Marlin 1 too ;) 
I think a cmd line flag would be nicer than env setting.

Thanks for support.

**Comment by wtarreau** [comment] 2021-02-01 00:34
Thanks for the report. That's funny because I thought "probably so few people will need it that we don't need a command line flag for this and the environment will be enough". Apparently I was wrong :-)  I'll add it, it's easy enough.

**Comment by wtarreau** [comment] 2021-02-01 15:16
Now done (argument is -L).

**Comment by wtarreau** [comment] 2021-02-01 15:20
Closing the issue since it's completed. Thanks both for the suggestions and the feedback.

**Closed as completed by wtarreau** 2021-02-01 15:20 UTC
